/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color Palette - Light Mode
        "on-surface-variant": "#3c4a3d",
        "secondary-fixed-dim": "#c4c7ca",
        "primary-fixed-dim": "#3de273",
        "on-secondary-fixed-variant": "#44474a",
        "surface-tint": "#006d2f",
        "on-tertiary-fixed-variant": "#4a4641",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#4c4842",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1e1b17",
        "surface-bright": "#f5faff",
        "secondary-fixed": "#e0e3e6",
        "surface-dim": "#d1dbe4",
        "surface-container-high": "#dfeaf2",
        "inverse-on-surface": "#e8f2fb",
        "surface-container": "#e5eff8",
        "surface": "#f5faff",
        "surface-container-low": "#eaf5fe",
        "primary-fixed": "#66ff8e",
        "on-surface": "#131d23",
        "on-primary-fixed-variant": "#005322",
        "on-primary-fixed": "#002109",
        "primary": "#006d2f",
        "outline-variant": "#bbcbb9",
        "surface-variant": "#d9e4ec",
        "on-tertiary": "#ffffff",
        "primary-container": "#25d366",
        "on-error-container": "#93000a",
        "inverse-surface": "#283238",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#e0e3e6",
        "outline": "#6c7b6b",
        "background": "#f5faff",
        "secondary": "#5c5f61",
        "surface-container-highest": "#d9e4ec",
        "tertiary": "#625e58",
        "on-secondary-container": "#626567",
        "error": "#ba1a1a",
        "on-background": "#131d23",
        "inverse-primary": "#3de273",
        "on-primary-container": "#005523",
        "on-secondary-fixed": "#191c1e",
        "tertiary-fixed": "#e8e1d9",
        "tertiary-container": "#bdb7b0",
        "tertiary-fixed-dim": "#ccc5be",
        "on-secondary": "#ffffff",
        // Dark Mode Colors
        "dark": {
          "on-surface-variant": "#bccbb9",
          "secondary-fixed-dim": "#44474a",
          "primary-fixed-dim": "#005322",
          "on-secondary-fixed-variant": "#c4c7ca",
          "surface-tint": "#66ff8e",
          "on-tertiary-fixed-variant": "#c9c4bd",
          "surface-container-lowest": "#0b1418",
          "on-tertiary-container": "#c9c4bd",
          "on-primary": "#003915",
          "on-tertiary-fixed": "#1e1b17",
          "surface-bright": "#1e2830",
          "secondary-fixed": "#44474a",
          "surface-dim": "#141c20",
          "surface-container-high": "#1e2830",
          "inverse-on-surface": "#1e2830",
          "surface-container": "#1c282e",
          "surface": "#161c20",
          "surface-container-low": "#181f23",
          "primary-fixed": "#005322",
          "on-surface": "#e1e9ed",
          "on-primary-fixed-variant": "#66ff8e",
          "on-primary-fixed": "#66ff8e",
          "primary": "#3de273",
          "outline-variant": "#44474a",
          "surface-variant": "#3f4a51",
          "on-tertiary": "#352f28",
          "primary-container": "#005322",
          "on-error-container": "#ffdad6",
          "inverse-surface": "#e1e9ed",
          "error-container": "#93000a",
          "on-error": "#690005",
          "secondary-container": "#44474a",
          "outline": "#5c6560",
          "background": "#0b1418",
          "secondary": "#c4c7ca",
          "surface-container-highest": "#3f4a51",
          "tertiary": "#c9c4bd",
          "on-secondary-container": "#e1e9ed",
          "error": "#ffb4ab",
          "on-background": "#e1e9ed",
          "inverse-primary": "#006d2f",
          "on-primary-container": "#66ff8e",
          "on-secondary-fixed": "#e1e9ed",
          "tertiary-fixed": "#4a4641",
          "tertiary-container": "#5c5650",
          "tertiary-fixed-dim": "#8c857c",
          "on-secondary": "#1c282e",
        },
        // Chat specific colors
        chat: {
          background: '#E5DDD5',
          sent: '#DCF8C6',
          received: '#FFFFFF',
          "dark-bg": '#0b1013',
          "dark-sent": '#005c4b',
          "dark-received": '#1e2830',
        }
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "chat-text": ["Inter"],
        "h2": ["Inter"],
        "body-base": ["Inter"],
        "h1": ["Inter"],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "chat-text": ["14.5px", {"lineHeight": "20px", "fontWeight": "400"}],
        "h2": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-base": ["15px", {"lineHeight": "22px", "fontWeight": "400"}],
        "h1": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      },
      spacing: {
        "xl": "32px",
        "lg": "24px",
        "sidebar_width": "320px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "chat_max_width": "800px",
        "unit": "4px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      boxShadow: {
        'soft': '0 2px 15px rgba(0, 0, 0, 0.08)',
        'medium': '0 4px 25px rgba(0, 0, 0, 0.12)',
        'strong': '0 8px 40px rgba(0, 0, 0, 0.16)',
        'chat': '0 1px 0.5px rgba(11, 20, 26, 0.13)',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}